### ISSUE TITLE
Font size of reservation title changes on different devices.

### ISSUE THREAD

**Issue by TheReverseSide** [ubikampus/reservator#100]
Particularly, a Samsung tablet resulted in the text being extremely small.
Line 346 of CalendarVisualizer.Java. It is hardcoded as a number, so not sure why it begins to scale depending on device.

**Comment by izrailit** [comment]
It's hardcorded in pixels, and scales because pixels are different size on different devices.

**Comment by izrailit** [comment]
Fixed, and pull request made, but I am not sure I got the sizes right.
