### ISSUE TITLE
Add "cancel reservation" button to OngoingReservationFragment

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#110]
This cancel button should animate the time slider to 0, which activates the existing handling of cancellations. Note that there needs to be space for 3 languages in the button.

**Comment by TheReverseSide** [comment]
The cancel_button branch has been published, the button is in the correct position, and is disabled when saving reservation changes.

**Comment by TheReverseSide** [comment]
An onClickListener has been placed, all that lacks is actually hooking it up to the correct method and animating it

**Comment by ptesavol** [comment]
Implemented the functionality and merged to the master.
