### ISSUE TITLE
Make app installable from command line

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#113]
The app should be made installable from command line without GUI intervention from the user. Also the setup vizard should be by-passable with command line parameters or similar mechanism.

**Comment by izrailit** [comment]
Do you mean through adb? Any app is already installable over adb.

**Comment by ptesavol** [comment]
What I mean by this is that we should be able to minimise the need of using the gui during installation of the app to new devices. Now one needs to go through the Startup vizard and to give permissions to the app using gui. I wonder could these permissions be given from the command line?

**Comment by scolphoy** [comment]
There is a command line option for granting the permissions.
`adb install -g reservator.apk`

```
  adb install [-lrtsdg] <file>
                               - push this package file to the device and install it
                                 (-l: forward lock application)
                                 (-r: replace existing application)
                                 (-t: allow test packages)
                                 (-s: install application on sdcard)
                                 (-d: allow version code downgrade (debuggable packages only))
                                 (-g: grant all runtime permissions)
```

**Comment by izrailit** [comment]
The permissions can be given from the commend line as scolphoy mentions above, but the setup wizard parameters would be a problem.

**Comment by izrailit** [comment]
Config from adb partially done. Can be configured for example:

adb shell am start -W -a android.intent.action.VIEW -d "reservator://change.reservator.settings?max_duration=120\&default_duration=45\&lang=en" com.futurice.android.reservator/.WizardActivity

the config variables are:
account
default_room
lang
max_duration
default_duration

The errors go to the Android log and can be read by adb logcat.

The account doesn't actually set the account yet, just goes to the account setting view.

Language only succeeds if the localization is available. Duration fails if it's not a number, if if both durations are given and default is longer than max. If for example only the default duration is given and it is higher than the existing max, it gets raised up to the existing max.

The current version assumes that the initial config has already happened, needs more work if we want to take the initial config into account.

**Comment by izrailit** [comment]
Done. Needs some extra testing by someone who isn't me.
