### ISSUE TITLE
Reservator showing "DISCONNECTED" on tablet restart

### ISSUE THREAD

**Issue by routerino** [ubikampus/reservator#154]
Application works as expected (thanks for the good work), except when the tablet does a restart. Upon restart, the tablet shows "DISCONNECTED", and requires a force close via settings to fix. I assume that this is because the reservator app (as the home screen application) loads before the mechanism it uses to connect to the exchange profile. Is there a way to gracefully recover? I don't want to have to go to every tablet running this and force close the home app after every restart.

Using exchange online with a meeting room account (mailbox enabled with password).

**Comment by ptesavol** [comment]
Reservator uses Android's ConnectivityManager to receive events for network getting connected/disconnected. In the onAvailable(Network network) callback Reservator checks whether the device is really connected to the Internet the same Android uses for captive portal detection https://stackoverflow.com/a/14030276), by checking if getting the URL http://clients3.google.com/generate_204 returns 204. If yes, Reservator hides the disconnected fragment. Could you check that there is no firewall blocking access to http://clients3.google.com/generate_204?

**Comment by routerino** [comment]
Thanks for the response, I have discovered in the past that our company web filter can do some screwy things under the assumption that their man-in-the-middle certificates are trusted.

I'll try setting the DNS manually on monday for the tablets and see if that resolves the issue.

**Comment by routerino** [comment]
Can confirm that changing DNS to dns.google has resolved the issue, thanks for the advice.
