### ISSUE TITLE
App crashes upon adjusting time outside of bounds

### ISSUE THREAD

**Issue by TheReverseSide** [ubikampus/reservator#56]
If the reservation is longer than our designated max (I have one that is all day) and you attempt to modify that and it is still outside of our bounds (e.g I tried to change it to 9 hours) it crashes. 
Upon deleting the event the crash no longer occurs.

Not a huge issue - just something we need to be aware of.

**Comment by ptesavol** [comment]
Can you tell more specifically about this?

**Comment by ptesavol** [comment]
How did you try to change the reservation length? Using the reservator UI?

**Comment by TheReverseSide** [comment]
Yeah, via edit functionality of the slider bar
