### ISSUE TITLE
Make APK available on github.io

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#66]
The APK of the app should be made available on github.io for testers to download and try. Instructions on making a github.io site: https://pages.github.com/

**Comment by ptesavol** [comment]
At second thought, maybe it is better to create a Release here at github and attach the apk into the release.

**Comment by ninjahoahong** [comment]
@ptesavol I think it is better to create release and attach it here to the github. And maybe remove the old release since we may want to use different keystore.

**Comment by ninjahoahong** [comment]
Another option to distribute the application to tester can be HockeyApp.

**Comment by ptesavol** [comment]
Uploaded the apk to github release.
