### ISSUE TITLE
Bring back "keep screen open functionality"

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#77]
Android should not go to sleep when Reservator is running.

**Comment by TheReverseSide** [comment]
Could we just turn on developer options, then select "Keep screen awake" while charging, and since it is always charging it will always be on?

**Comment by ptesavol** [comment]
I think I already brought this in from the old code. Is the feature not working?

**Comment by TheReverseSide** [comment]
It is working, just wanted to check if it has been fixed and whether or not we can close this
