### ISSUE TITLE
Bring back the clock, maybe also date and week number

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#90]
Got some feedback from testers. The tablet acts naturally as a wall clock and calendar, answering at one look to questions: what time is it? what date is it, what week is it?

I agree that we should bring back the clock to the user interface. Maybe also the date and week number.

**Comment by TheReverseSide** [comment]
Presumably the day and week will go in the top margin of the DayCalendar, where they were before, but what about the time? We currently have the clock sitting in the bottom fragment, unused

**Comment by ptesavol** [comment]
Yes, we can start by bringing back the old ones, and making them look a little better.

**Comment by TheReverseSide** [comment]
Working on this issue in bring_clock(s)_back branch

**Comment by ptesavol** [comment]
The clock is now back.
