### ISSUE TITLE
Add information (i) button and information popup

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#91]
A small button with "i" ison should be added to the UI. This should pop up a information window, that tells 
-Software name and version
- Link to github for feedback
- The github link as QR code

**Comment by TheReverseSide** [comment]
I have added an ImageButton on the info_button branch which I will publish soon, but it has been very difficult getting Android studio to accept the correct, UoH styleguide approved icon.

**Comment by TheReverseSide** [comment]
The clock and button are in position, and the basic popup xml has been made, but the button needs to be connected to display the xml

**Comment by ptesavol** [comment]
Added the button and the info window. Content and styling is still needed.
